version: '3.8'

services:
  customer_segmentation_engine:
    build:
      context: ./customer_segmentation_engine
    ports:
      - "5000:5000"
    networks:
      - mynetwork

  prescriptive_analytics_engine:
    build:
      context: ./prescriptive_analytics_engine
    ports:
      - "5001:5000"
    networks:
      - mynetwork

  sales_forecasting_engine:
    build:
      context: ./sales_forecasting_engine
    ports:
      - "5002:5000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
